/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: policy.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _POLICY_H_
#define _POLICY_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef policy__ns
#define policy__ns 1454482831
#define policy__ns_id "http://psefabric/policy"
#define policy__ns_uri "http://psefabric/policy"
#endif

#define policy_destination_addresses 117006563
#define policy_source_addresses 1549172421
#define policy_zone 1765671331
#define policy_policy 1919655803
#define policy_address_set 1119034972
#define policy_destination_port_range 1765771145
#define policy_address_set_name 861660896
#define policy_address_name 827307462
#define policy_structure 1315288478
#define policy_applications 2097670973
#define policy_packet_handling 513646788
#define policy_application_set_name 387173641
#define policy_match 1501964518
#define policy_policy_name 248830179
#define policy_addresses 1825332052
#define policy_vlan 71481437
#define policy_interface 221572658
#define policy_lower_port 1773740620
#define policy_prot 2040988365
#define policy_ipv4_prefix 1997304091
#define policy_application_set 1103172502
#define policy_vrf 1281310328
#define policy_application_sets 1233365936
#define policy_dc 398405326
#define policy_permit 1901628419
#define policy_source_port_range 1089949806
#define policy_policies 764028492
#define policy_ports 1554580266
#define policy_deny 1028777810
#define policy_then 106430948
#define policy_address_sets 1587002729
#define policy_upper_port 650228129
#define policy_device 617911018
#define policy_application_name 1709973133

#ifdef __cplusplus
}
#endif

#endif
